name: one_sixteen
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get:
  #get_cli: ^1.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic_mono: any

flutter:
  uses-material-design: true