name: one_sixteen
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  audioplayers: ^0.20.1
  flutter:
    sdk: flutter
  get:

  #get_cli: ^1.7.1

dev_dependencies:
  flutter_launcher_icons:
    git:
      url: https://github.com/Davenchy/flutter_launcher_icons.git
      ref: fixMinSdkParseFlutter2.8
  flutter_test:
    sdk: flutter
  pedantic_mono: any

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/images/
    - assets/sounds/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"

